/**
 * This file was auto-generated by OpenAPI Generator (https://openapi-generator.tech) from the OpenAPI specification for the Petstore API. Do not edit this file manually.
 * The tag model defines the structure of a tag object, which includes an id and a name. The module also provides three example tag objects, tag1, tag2, and tag3, each with unique id and name values. These tag objects can be used in other parts of the application to represent tags associated with pets or other entities. The module exports the tag type and the example tag objects for use in other modules of the application.
 */
type tag={
    id:number;
    name:string;
}
/**
 * Example tag objects
 * tag1 represents a tag with the name "tag1" and an id of 1.
 * tag2 represents a tag with the name "tag2" and an id of 2.
 * tag3 represents a tag with the name "tag3" and an id of 3.
 * These tag objects can be used to categorize or label pets or other entities in the application, allowing for easier organization and retrieval of information based on tags. The module exports the tag type and the example tag objects for use in other parts of the application, enabling developers to easily import and utilize these tags wherever needed. 
 */


let tag1:tag={
    id:1,
    name:"tag1"     
}
/**
 * Example tag objects
 * tag2 represents a tag with the name "tag2" and an id of 2.
 * tag3 represents a tag with the name "tag3" and an id of 3.
 * These tag objects can be used to categorize or label pets or other entities in the application, allowing for easier organization and retrieval of information based on tags. The module exports the tag type and the example tag objects for use in other parts of the application, enabling developers to easily import and utilize these tags wherever needed. 
 */
let tag2:tag={
    id:2,   
    name:"tag2"
}
/**
 * Example tag object
 * tag3 represents a tag with the name "tag3" and an id of 3.
 * This tag object can be used to categorize or label pets or other entities in the application, allowing for easier organization and retrieval of information based on tags. The module exports the tag type and the example tag objects for use in other parts of the application, enabling developers to easily import and utilize these tags wherever needed.   
 */
let tag3:tag={              
    id:3,
    name:"tag3"
}
export {tag,tag1,tag2,tag3}